=== polfarr/playlist/albums/album.dtd
<!DOCTYPE album[

<!ELEMENT album (title, cover?, artists, songs)>
<!ATTLIST album id CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>

<!ELEMENT cover>
<!ATTLIST cover src CDATA #REQUIRED>

<!ELEMENT artists (artist+)>
<!ELEMENT artist (#PCDATA)>
<!ATTLIST artist id CDATA #REQUIRED>
<!ATTLIST artist roles CDATA #IMPLIED>

<!ELEMENT songs (song+)>
<!ELEMENT song (#PCDATA)>
<!ATTLIST song id CDATA #REQUIRED>

]>

=== polfarr/playlist/albums/album1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE album SYSTEM "album.dtd">
<album id="1">
	<title>LOOM</title>
	<cover src="loom.jpg" />
	<artists>
		<artist id="1">Imagine Dragons</artist>
	</artists>
	<songs>
		<song id="1">Eyes Closed</song>
		<song id="2">Nice to Meet You</song>
		<song id="3">Wake Up</song>
		<song id="4">Take Me to the Beach</song>
	</songs>
</album>

=== polfarr/playlist/albums/album2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE album SYSTEM "album.dtd">
<album id="2">
	<title>Cracker Island</title>
	<cover src="crackerisland.jpg" />
	<artists>
		<artist id="2">Gorillaz</artist>
	</artists>
	<songs>
		<song id="5">Cracker Island (feat. Thundercat)</song>
		<song id="6">The Tired Influencer</song>
		<song id="7">Tarantula</song>
		<song id="8">Silent Running (feat. Adeleye Omotayo)</song>
        <song id="9">New Gold (feat. Tame Impala & Bootie Brown)</song>
        <song id="10">Baby Queen</song>
        <song id="11">Skinny Ape</song>
        <song id="12">Possession Island (feat. Beck)</song>
	</songs>
</album>

=== polfarr/playlist/albums/album3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE album SYSTEM "album.dtd">
<album id="3">
	<title>Night Visions</title>
	<cover src="nightvisions.jpg" />
	<artists>
		<artist id="1">Imagine Dragons</artist>
	</artists>
	<songs>
		<song id="13">Radioactive</song>
		<song id="14">Tiptoe</song>
		<song id="15">It's Time</song>
		<song id="16">Demons</song>
        <song id="17">On Top of the World</song>
        <song id="18">Amsterdam</song>
        <song id="19">Hear Me</song>
        <song id="20">Every Night</song>
        <song id="21">Nothing Left to Say / Rocks</song>
        <song id="22">Bleeding Out</song>
        <song id="23">Underdog</song>
	</songs>
</album>
